// apps/timer/src/lib/components/Timer.svelte
<script lang="ts">
  import { goto } from '$app/navigation'
  import { Button } from '@tallytop/ui'
  import { Howl } from 'howler'
  import { nanoid } from 'nanoid'
  import parseMs from 'parse-ms'
  import ArrowCounterClockwise from 'phosphor-svelte/lib/ArrowCounterClockwise'
  import Eye from 'phosphor-svelte/lib/eye'
  import Play from 'phosphor-svelte/lib/play'
  import Stop from 'phosphor-svelte/lib/stop'

  let endTime: number
  let elapsed = 0
  let status = 'stopped'

  export let duration = 5 * 60 * 1000
  let time = parseMs(duration)

  const sound = {
    beep: new Howl({ src: '/sounds/beep.mp3' }),
    end: new Howl({ src: '/sounds/end.mp3' })
  }
  export let beeps = [0, 60, 5, 4, 3, 2, 1]
  let playedBeeps: number[] = []

  export let viewMode = false
  export let id: string = nanoid()

  function start() {
    endTime = Date.now() + duration - elapsed
    status = 'started'
  }

  function stop() {
    const remaining = endTime - Date.now()
    elapsed = duration - remaining
    status = 'stopped'
  }

  function reset() {
    time = parseMs(duration)
    elapsed = 0
    status = 'stopped'
    playedBeeps = []
  }

  function tick() {
    if (status === 'running') {
      let remaining = endTime - Date.now()

      if (remaining < 0) {
        remaining = 0
      }
      if (remaining === 0) {
        stop()
        sound.end.play()
      }

      time = parseMs(remaining)

      const seconds = Math.ceil(remaining / 1000)

      if (
        !playedBeeps.includes(seconds) &&
        (seconds === Math.ceil(duration / 1000) || beeps.includes(seconds))
      ) {
        sound.beep.play()
        playedBeeps = [...playedBeeps, seconds]
      }

      requestAnimationFrame(tick)
    }
  }

  function view() {
    goto(`/${id}`)
  }

  $: {
    if (status === 'started') {
      status = 'running'
      tick()
    }
  }
</script>

<div class="font-mono text-[15vw]">
  {[
    String(time.seconds + time.milliseconds / 1000 > 59 ? time.minutes + 1 : time.minutes).padStart(
      2,
      '0'
    ),
    String(Math.ceil(time.seconds + time.milliseconds / 1000) % 60).padStart(2, '0')
  ].join(':')}
</div>

{#if !viewMode}
  <div class="flex gap-10 text-4xl">
    {#if status === 'stopped'}
      <Button class="bg-emerald-200 px-10 py-5" on:click={start}><Play /></Button>
    {:else}
      <Button class="bg-orange-200 px-10 py-5" on:click={stop}><Stop /></Button>
    {/if}
    <Button class="px-10 py-5" on:click={reset}><ArrowCounterClockwise /></Button>
    <Button class="px-10 py-5" on:click={view}><Eye /></Button>
  </div>
{/if}

// apps/timer/components/Timer.tsx
import parseMs from "parse-ms";
import { useCallback, useEffect, useRef, useState } from "react";
import { Button } from "ui";
import { ArrowCounterClockwise, Play, Stop } from "ui/icons";

type TimerProps = {
  duration: number;
  onSound: (type: string) => void;
};

export default function Timer({ duration, onSound }: TimerProps) {
  const { time, start, stop, reset, status } = useTimer(duration, onSound);
  const { hours, minutes, seconds, milliseconds } = time;
  return (
    <>
      <div className="font-mono text-[15vw]">
        {hours ? `${String(hours).padStart(2, "0")}:` : null}
        {String(
          seconds + milliseconds / 1000 > 59 ? minutes + 1 : minutes
        ).padStart(2, "0")}
        :
        {String(Math.ceil(seconds + milliseconds / 1000) % 60).padStart(2, "0")}
      </div>
      <div className="flex gap-10 text-4xl">
        {status === "running" ? (
          <Button className="bg-orange-200 px-10 py-5" onClick={stop}>
            <Stop />
          </Button>
        ) : (
          <Button className="bg-emerald-200 px-10 py-5" onClick={start}>
            <Play />
          </Button>
        )}
        <Button className="px-10 py-5" onClick={reset}>
          <ArrowCounterClockwise />
        </Button>
      </div>
    </>
  );
}

const defaultBeeps = [
  60, // 0:01:00
  5, // 0:00:05
  4, // 0:00:04
  3, // 0:00:03
  2, // 0:00:02
  1, // 0:00:01
];

const useTimer = (duration: number, onSound: (type: string) => void) => {
  const [time, setTime] = useState(parseMs(duration));
  const beeps = useRef(defaultBeeps);
  const endTime = useRef(Date.now());
  const elapsed = useRef(0);
  const isRunning = useRef(false);
  const [status, setStatus] = useState("reset");

  const start = () => {
    endTime.current = Date.now() + duration - elapsed.current;
    isRunning.current = true;
    setStatus("running");
    if (elapsed.current === 0) {
      onSound("beep");
    }
  };

  const stop = useCallback(() => {
    const remaining = endTime.current - Date.now();
    elapsed.current = duration - remaining;
    isRunning.current = false;
    setStatus("stopped");
  }, [duration]);

  const reset = useCallback(() => {
    setTime(parseMs(duration));
    elapsed.current = 0;
    beeps.current = defaultBeeps;
    isRunning.current = false;
    setStatus("reset");
  }, [duration]);

  const tick = useCallback(() => {
    if (isRunning.current) {
      let remaining = endTime.current - Date.now();
      if (remaining < 0) {
        remaining = 0;
      }
      setTime(parseMs(remaining));
      const second = Math.floor(remaining / 1000) + 1;
      if (beeps.current.includes(second)) {
        beeps.current = beeps.current.filter((v) => v !== second);
        onSound("beep");
      }
      if (remaining === 0) {
        stop();
        onSound("end");
      }
    }
    requestAnimationFrame(tick);
  }, [stop]);

  useEffect(() => {
    requestAnimationFrame(tick);
  }, [tick]);

  useEffect(() => {
    reset();
  }, [reset, duration]);

  return { time, start, stop, reset, status };
};
