// app/routes/timer.tsx
import parseMs from 'parse-ms'
import { useCallback, useEffect, useRef, useState } from 'react'

const defaultBeeps = [
  2 * 60 * 60, // 2:00:00
  1 * 60 * 60, // 1:00:00
  60,          // 0:01:00
  5,           // 0:00:05
  4,           // 0:00:04
  3,           // 0:00:03
  2,           // 0:00:02
  1            // 0:00:01
]

const useTimer = (duration: number) => {
  const [state, setState] = useState({
    duration,
    time: parseMs(duration),
  })
  const sound = useRef<any>()
  const beeps = useRef(defaultBeeps)
  const endDate = useRef(new Date())
  const elapsed = useRef(0)
  const isRunning = useRef(false)

  const start = () => {
    endDate.current = new Date(Date.now() + duration - elapsed.current)
    isRunning.current = true
    if (elapsed.current === 0) {
      sound.current.play('beep')
    }
  }

  const stop = () => {
    const remaining = endDate.current.getTime() - Date.now()
    elapsed.current = duration - remaining
    isRunning.current = false
  }

  const reset = useCallback(() => {
    setState((state) => ({
      ...state,
      time: parseMs(state.duration),
    }))
    elapsed.current = 0
    isRunning.current = false
    beeps.current = defaultBeeps
  }, [])

  const tick = useCallback(() => {
    if (isRunning.current) {
      let remaining = endDate.current.getTime() - Date.now()
      if (remaining < 0) {
        remaining = 0
      }
      const time = parseMs(remaining)
      setState((state) => ({
        ...state,
        time,
      }))
      const second = Math.floor(remaining / 1000) + 1
      if (beeps.current.includes(second)) {
        beeps.current = beeps.current.filter((v) => v !== second)
        sound.current.play('beep')
      }
      if (remaining === 0) {
        stop()
        sound.current.play('end')
      }
    }
    requestAnimationFrame(tick)
  }, [])

  useEffect(() => {
    setState((state) => ({ ...state, duration }))
    reset()
  }, [reset, duration])

  useEffect(() => {
    requestAnimationFrame(tick)
  }, [tick])

  useEffect(() => {
    import('@pixi/sound').then(({ sound: pixiSound }) => {
      if (sound.current) {
        // This runs twice for some reason!
        return
      }
      sound.current = pixiSound
      sound.current.add('beep', '/sounds/beep.mp3')
      sound.current.add('end', '/sounds/end.mp3')
    })
  }, [])

  return { ...state, isRunning: isRunning.current, start, stop, reset }
}

export default function Timer() {
  const [duration, setDuration] = useState(5 * 60 * 1000)
  const beep = useRef<any>()
  const { start, stop, reset, time } = useTimer(duration, beep)
  const { hours, minutes, seconds, milliseconds } = time

  return (
    <div className="flex flex-1 flex-col items-center justify-center gap-10">
      <div className="font-mono text-[15vw] text-red">
        {hours ? `${String(hours).padStart(2, '0')}:` : null}
        {String(minutes).padStart(2, '0')}:{String(seconds).padStart(2, '0')}
        <span className="text-[7vw]">
          .{String(milliseconds).padStart(3, '0')}
        </span>
      </div>
      <div className="flex gap-10 text-4xl">
        <button className="button px-10 py-5" onClick={start}>
          Start
        </button>
        <button className="button bg-black px-10 py-5" onClick={stop}>
          Stop
        </button>
        <button className="button bg-black px-10 py-5" onClick={reset}>
          Reset
        </button>
      </div>
      <div className="flex gap-10 text-2xl">
        <button
          className="button bg-black"
          onClick={() => setDuration(3 * 60 * 60 * 1000)}
        >
          3 hrs
        </button>
        <button
          className="button bg-black"
          onClick={() => setDuration(5 * 60 * 1000)}
        >
          5 mins
        </button>
        <button
          className="button bg-black"
          onClick={() => setDuration(4 * 60 * 1000)}
        >
          4 mins
        </button>
        <button
          className="button bg-black"
          onClick={() => setDuration(2 * 60 * 1000)}
        >
          2 mins
        </button>
      </div>
    </div>
  )
}

// apps/timer/src/lib/components/Timer.svelte
<script lang="ts">
  import { goto } from '$app/navigation'
  import { Button } from '@tallytop/ui'
  import { Howl } from 'howler'
  import { nanoid } from 'nanoid'
  import parseMs from 'parse-ms'
  import ArrowCounterClockwise from 'phosphor-svelte/lib/ArrowCounterClockwise'
  import Eye from 'phosphor-svelte/lib/eye'
  import Play from 'phosphor-svelte/lib/play'
  import Stop from 'phosphor-svelte/lib/stop'

  let endTime: number
  let elapsed = 0
  let status = 'stopped'

  export let duration = 5 * 60 * 1000
  let time = parseMs(duration)

  const sound = {
    beep: new Howl({ src: '/sounds/beep.mp3' }),
    end: new Howl({ src: '/sounds/end.mp3' })
  }
  export let beeps = [0, 60, 5, 4, 3, 2, 1]
  let playedBeeps: number[] = []

  export let viewMode = false
  export let id: string = nanoid()

  function start() {
    endTime = Date.now() + duration - elapsed
    status = 'started'
  }

  function stop() {
    const remaining = endTime - Date.now()
    elapsed = duration - remaining
    status = 'stopped'
  }

  function reset() {
    time = parseMs(duration)
    elapsed = 0
    status = 'stopped'
    playedBeeps = []
  }

  function tick() {
    if (status === 'running') {
      let remaining = endTime - Date.now()

      if (remaining < 0) {
        remaining = 0
      }
      if (remaining === 0) {
        stop()
        sound.end.play()
      }

      time = parseMs(remaining)

      const seconds = Math.ceil(remaining / 1000)

      if (
        !playedBeeps.includes(seconds) &&
        (seconds === Math.ceil(duration / 1000) || beeps.includes(seconds))
      ) {
        sound.beep.play()
        playedBeeps = [...playedBeeps, seconds]
      }

      requestAnimationFrame(tick)
    }
  }

  function view() {
    goto(`/${id}`)
  }

  $: {
    if (status === 'started') {
      status = 'running'
      tick()
    }
  }
</script>

<div class="font-mono text-[15vw]">
  {[
    String(time.seconds + time.milliseconds / 1000 > 59 ? time.minutes + 1 : time.minutes).padStart(
      2,
      '0'
    ),
    String(Math.ceil(time.seconds + time.milliseconds / 1000) % 60).padStart(2, '0')
  ].join(':')}
</div>

{#if !viewMode}
  <div class="flex gap-10 text-4xl">
    {#if status === 'stopped'}
      <Button class="bg-emerald-200 px-10 py-5" on:click={start}><Play /></Button>
    {:else}
      <Button class="bg-orange-200 px-10 py-5" on:click={stop}><Stop /></Button>
    {/if}
    <Button class="px-10 py-5" on:click={reset}><ArrowCounterClockwise /></Button>
    <Button class="px-10 py-5" on:click={view}><Eye /></Button>
  </div>
{/if}
