// app/routes/index.tsx
import { Link } from '@remix-run/react'

export default function Index() {
  const linkClassName =
    'flex flex-1 items-center justify-center hover:opacity-50'
  return (
    <div className="flex flex-1 flex-col items-center text-[8vw]">
      <Link className={linkClassName} to="/climb">
        CLIMB!
      </Link>
      <img src="/images/snow-mountain.svg" alt="Divider" />
      <Link className={linkClassName} to="/qualifiers">
        QUALIFIERS
      </Link>
      <img src="/images/snow-mountain.svg" alt="Divider" />
      <Link className={linkClassName} to="/problems">
        PROBLEMS
      </Link>
      <img src="/images/snow-mountain.svg" alt="Divider" />
      <Link className={linkClassName} to="/final">
        FINALS
      </Link>
    </div>
  )
}

// apps/rocka-manila/src/routes/+page.svelte
<div class="flex flex-col bg-rockamanila-bg min-h-screen justify-center items-center p-10">
  <div class="max-w-screen-sm flex flex-col gap-10">
    <img src="/images/rocka-manila-logo.png" alt="Rocka Manila" />
    <a href="/novice_men/results/finals" class="active:scale-95"
      ><img src="/images/finals.svg" alt="Finals" /></a
    >
  </div>
</div>
